name: Deploy

on:
  push:
    tags:
    - v*

jobs:

  deploy-build-ubuntu:
    name: Deploy (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup conan
      run: |
        pip3 install setuptools
        pip3 install conan
        ~/.local/bin/conan config install https://github.com/iceshard-engine/conan-config.git
    - name: Create (clang-9)
      run: |
        ~/.local/bin/conan create . lua-filesystem/1.8.0@iceshard/stable --profile clang-9.0-linux-x86_64
    - name: Create (clang-10)
      run: |
        ~/.local/bin/conan create . lua-filesystem/1.8.0@iceshard/stable --profile clang-10.0-linux-x86_64
    - name: Deploy
      run: |
        ~/.local/bin/conan user iceshard -r conan-iceshard -p ${{ secrets.CONAN_PASSWORD }}
        ~/.local/bin/conan upload -r conan-iceshard lua-filesystem/1.8.0@iceshard/stable --all

  deploy-build-windows:
    name: Deploy (Windows)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup conan
      run: |
        pip3 install setuptools
        pip3 install conan
        conan config install https://github.com/iceshard-engine/conan-config.git
    - name: Export
      run: |
        conan create . lua-filesystem/1.8.0@iceshard/stable
    - name: Deploy
      run: |
        conan user iceshard -r conan-iceshard -p ${{ secrets.CONAN_PASSWORD }}
        conan upload -r conan-iceshard lua-filesystem/1.8.0@iceshard/stable --all
